include: package:effective_dart/analysis_options.yaml
# include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false
  errors:
    argument_type_not_assignable: info

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
