name: superbingo
description: A new Flutter application.

version: 1.0.0+20
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  connectivity: ^2.0.0 # null-safety with ^3.0.0-nullsafety.3
  rxdart: ^0.25.0 # null-safety with ^0.26.0-nullsafety.1
  overlay_support: ^1.0.4 # null-safety with ^1.2.0-nullsafety.0
  share: ^0.6.5+4 # null-safety with ^2.0.0-nullsafety.2
  shared_preferences: ^0.5.12+4 # null-safety with ^2.0.0-nullsafety

  firebase_core: ^0.7.0 # null-safety with ^0.8.0-nullsafety.0
  firebase_auth: ^0.20.0+1 # null-safety with ^0.21.0-nullsafety.0
  firebase_crashlytics: ^0.4.0+1 # null-safety with ^0.5.0-1.0.nullsafety.2
  cloud_firestore: ^0.16.0 # null-safety with ^0.17.0-1.0.nullsafety.0
  firedart: ^0.8.3 # no null-safety - only needed for desktop UI debugging

  provider: ^4.3.3 # null-safety with ^5.0.0-nullsafety.3
  flutter_bloc: ^6.1.2 # null-safety with ^7.0.0-nullsafety.1
  equatable: ^1.2.6 # null-safety with ^2.0.0-nullsafety.1
  responsive_builder: ^0.3.0 # null-safety with ^0.4.0-nullsafety.1

  # helper
  vector_math: ^2.0.8 # null-safety with ^2.1.0-nullsafety.5
  uuid: ^2.2.2 # null-safety with ^3.0.0-nullsafety.0
  supercharged: ^1.12.0 # null-safety with ^2.0.0-nullsafety.1

  #Json Serialization
  json_annotation: ^3.1.1 # null-safety with ^4.0.0-nullsafety.0

  win32: ^1.7.4 # null-safety with ^2.0.0-nullsafety.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1 # no null-safety
  json_serializable: ^3.5.1 # null-safety with ^4.0.0-nullsafety.0
  flutter_native_splash: ^0.3.0 # no null-safety
  bloc_test: ^7.1.0 # no null-safety
  cloud_firestore_mocks: ^0.6.0 # no null-safety
  firebase_auth_mocks: ^0.5.1 # no null-safety

  effective_dart: ^1.3.0
  lint: ^1.5.1

flutter_native_splash:
  color: "FF6E40"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
