name: superbingo
description: A new Flutter application.

version: 1.0.0+20
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  connectivity: ^3.0.3
  connectivity_for_web: ^0.4.0
  rxdart: ^0.26.0 
  overlay_support: ^1.2.0
  share: ^2.0.1
  shared_preferences: ^2.0.5

  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_crashlytics: ^1.0.0
  cloud_firestore: ^1.0.1
  # firedart: ^0.8.3 # no null-safety - only needed for desktop UI debugging

  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  responsive_builder: ^0.4.0-nullsafety.1

  # helper
  vector_math: ^2.1.0
  uuid: ^3.0.1
  supercharged: ^2.0.0
  collection: ^1.15.0

  #Json Serialization
  json_annotation: ^4.0.1

  win32: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  flutter_native_splash: ^1.1.4+1
  flutter_launcher_icons: ^0.9.0
  bloc_test: ^8.0.0
  # cloud_firestore_mocks: ^0.7.0
  # firebase_auth_mocks: ^0.6.0

  effective_dart: ^1.3.1
  lint: ^1.5.3

flutter_native_splash:
  color: "FF6E40"
  image: assets/app_icon_with_shadow_no_background.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  # adaptive_icon_background: "#FF2E3037"
  adaptive_icon_foreground: assets/app_icon.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icon.png
    - assets/app_icon_transparent.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
