on:
  push:
    branches:
      - "master"
    paths:
      - "superbingo/pubspec.yaml"
      - ".github/workflows/main.yaml"
name: Test, Build and Release apk
jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.6'
        channel: 'beta'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --split-per-abi
    - name: upload android artifacts
      uses: actions/upload-artifact@v1
      with:
        name: superbingo-android
        path: build/app/outputs/apk/release/
    - name: release android-artifacts
      uses: ncipollo/release-action@v1
      with: 
        artifacts: build/app/outputs/apk/release/
        token: ${{ secrets.ACTIONS_TOKEN }}
        tag: v0.3
  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.6'
        channel: 'beta'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios  --release --no-codesign
    - name: upload ios artifacts
      uses: actions/upload-artifact@v1
      with:
        name: superbingo-ios
        path: build/ios/iphoneos/Runner.app
    - name: release android-artifacts
      uses: ncipollo/release-action@v1
      with: 
        artifacts: build/ios/iphoneos/Runner.app
        token: ${{ secrets.ACTIONS_TOKEN }}
        tag: v0.3
